### ISSUE TITLE
Messy CSS

### ISSUE THREAD

**Issue by aidalgol** [nicferrier/elwikicreole#16]
`creole-wiki` outputs rather messy and redundant CSS.  For example (reformatted for readability),

``` css
span.keyword {
  color: #d3d3d3;
  font-weight: 700;
  font-family: DejaVu Sans Mono;
  font-style: normal;
  font-stretch: normal;
  font-size: 10pt;
  text-decoration: none;
}
span.keyword a {
  color: #d3d3d3;
  font-weight: 700;
  font-family: DejaVu Sans Mono;
  font-style: normal;
  font-stretch: normal;
  font-size: 10pt;
  text-decoration: underline;
}
span.keyword {
  color: #a020f0;
}
```

Most of `span.keyword a` is redundant, and it's defining the color twice, differently each time.  `font-family` should also be set to the more generic `monspace`, instead of naming a specific font with no fallback.

This is a bug in htmlize, and not creole.el itself, isn't it?
